/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiPayPalCaptureOrderOrderIdPost } from '../fn/pay-pal/api-pay-pal-capture-order-order-id-post';
import { ApiPayPalCaptureOrderOrderIdPost$Params } from '../fn/pay-pal/api-pay-pal-capture-order-order-id-post';
import { apiPayPalCreateOrderPost } from '../fn/pay-pal/api-pay-pal-create-order-post';
import { ApiPayPalCreateOrderPost$Params } from '../fn/pay-pal/api-pay-pal-create-order-post';

@Injectable({ providedIn: 'root' })
export class PayPalService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiPayPalCreateOrderPost()` */
  static readonly ApiPayPalCreateOrderPostPath = '/api/PayPal/create-order';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPayPalCreateOrderPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPayPalCreateOrderPost$Response(params?: ApiPayPalCreateOrderPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiPayPalCreateOrderPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPayPalCreateOrderPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPayPalCreateOrderPost(params?: ApiPayPalCreateOrderPost$Params, context?: HttpContext): Observable<void> {
    return this.apiPayPalCreateOrderPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiPayPalCaptureOrderOrderIdPost()` */
  static readonly ApiPayPalCaptureOrderOrderIdPostPath = '/api/PayPal/capture-order/{orderId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPayPalCaptureOrderOrderIdPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPayPalCaptureOrderOrderIdPost$Response(params: ApiPayPalCaptureOrderOrderIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiPayPalCaptureOrderOrderIdPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPayPalCaptureOrderOrderIdPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPayPalCaptureOrderOrderIdPost(params: ApiPayPalCaptureOrderOrderIdPost$Params, context?: HttpContext): Observable<void> {
    return this.apiPayPalCaptureOrderOrderIdPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
